# Generated by Django 2.1.7 on 2020-10-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100)),
                ('task', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, default='00:00', max_length=10)),
                ('end_time', models.CharField(blank=True, default='00:00', max_length=10)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('issue', models.TextField(blank=True)),
                ('approver_decision', models.CharField(blank=True, max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approver_reject_reason', models.TextField(blank=True)),
                ('approver_comment', models.TextField(blank=True)),
                ('admin_decision', models.CharField(blank=True, max_length=20)),
                ('admin_approval_date', models.DateTimeField(blank=True, null=True)),
                ('admin_reject_reason', models.TextField(blank=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('opened_by', models.CharField(blank=True, max_length=20)),
                ('edited_by', models.CharField(blank=True, max_length=20)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_admin_id1', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_manager_by1', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_employee_to1', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetRepporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=20)),
                ('manager_name', models.CharField(blank=True, max_length=20)),
                ('admin_name', models.CharField(blank=True, max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_admin1', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_employee1', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_manage1r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
